"""empty message

Revision ID: 3d5a40716693
Revises: d6b6a94d540e
Create Date: 2021-08-29 00:01:38.420592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5a40716693'
down_revision = 'd6b6a94d540e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('work_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worker', 'work', ['work_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_column('worker', 'work_id')
    # ### end Alembic commands ###
