"""empty message

Revision ID: 839f4d7207d7
Revises: b8036a957e19
Create Date: 2021-08-29 03:55:57.841059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839f4d7207d7'
down_revision = 'b8036a957e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('work_plan_title_key', 'work_plan', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('work_plan_title_key', 'work_plan', ['title'])
    # ### end Alembic commands ###
