"""empty message

Revision ID: b8036a957e19
Revises: 3d5a40716693
Create Date: 2021-08-29 03:35:37.644874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8036a957e19'
down_revision = '3d5a40716693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'work_plan', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_plan', type_='unique')
    # ### end Alembic commands ###
