"""empty message

Revision ID: ee9262a7a620
Revises: bee970b6a137
Create Date: 2021-09-02 18:21:08.929246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9262a7a620'
down_revision = 'bee970b6a137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('work_plan_title_key', 'work_plan', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('work_plan_title_key', 'work_plan', ['title'])
    # ### end Alembic commands ###
